USE TaskManager
GO

CREATE TABLE [User]
(
	Id         INTEGER IDENTITY(1,1) PRIMARY KEY,
	FullName   VARCHAR(40),
	Email      VARCHAR(255) UNIQUE NOT NULL,
	[Password] NVARCHAR(32) NOT NULL,
)
GO

ALTER TABLE Task
	DROP COLUMN Client
GO

ALTER TABLE Task
	ADD Client INTEGER
GO

ALTER TABLE Task
	ADD FOREIGN KEY (Client) REFERENCES [User](Id)
GO