//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki.Resources.Views {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wiki.Resources.Views.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string Anglais {
            get {
                return ResourceManager.GetString("Anglais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connexion.
        /// </summary>
        public static string Connexion {
            get {
                return ResourceManager.GetString("Connexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contenu.
        /// </summary>
        public static string Contenu {
            get {
                return ResourceManager.GetString("Contenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se créer un compte utilisateur.
        /// </summary>
        public static string CreerCompte {
            get {
                return ResourceManager.GetString("CreerCompte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Déconnexion.
        /// </summary>
        public static string Deconnexion {
            get {
                return ResourceManager.GetString("Deconnexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fermer.
        /// </summary>
        public static string Fermer {
            get {
                return ResourceManager.GetString("Fermer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Français.
        /// </summary>
        public static string Francais {
            get {
                return ResourceManager.GetString("Francais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inscription.
        /// </summary>
        public static string Inscription {
            get {
                return ResourceManager.GetString("Inscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface de connexion au wiki.
        /// </summary>
        public static string InterfaceConnexion {
            get {
                return ResourceManager.GetString("InterfaceConnexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changer de mot de passe.
        /// </summary>
        public static string MdpChanger {
            get {
                return ResourceManager.GetString("MdpChanger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe oublié?.
        /// </summary>
        public static string MdpOublie {
            get {
                return ResourceManager.GetString("MdpOublie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil.
        /// </summary>
        public static string Profil {
            get {
                return ResourceManager.GetString("Profil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sauvegarder.
        /// </summary>
        public static string Sauvegarder {
            get {
                return ResourceManager.GetString("Sauvegarder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se connecter.
        /// </summary>
        public static string SeConnecter {
            get {
                return ResourceManager.GetString("SeConnecter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S&apos;inscrire.
        /// </summary>
        public static string SInscrire {
            get {
                return ResourceManager.GetString("SInscrire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se souvenir de moi.
        /// </summary>
        public static string SouvenirMoi {
            get {
                return ResourceManager.GetString("SouvenirMoi", resourceCulture);
            }
        }
    }
}
